config/routes.rb
Salticidae::Application.routes.draw do

  resource :cert, :only => [:show]

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :sessions, :only => [:new, :create, :update, :destroy]

  get "sign_up" => "users#new", :as => "sign_up"
  resources :users, :only => [:new, :create]

  root :to => "home#index"

end

app/models/cert.rb
class Cert < CouchRest::Model::Base

  timestamps!

  property :random, Float, :accessible => false

  before_validation :set_random, :attach_zip, :on => :create

  validates :random, :presence => true,
    :numericality => {:greater_than => 0, :less_than => 1}

  validates :zipped, :presence => true

  design do
    view :by_random
  end

  class << self
    def sample
      self.by_random.startkey(rand).first || self.by_random.first
    end

    def pick_from_pool
      cert = self.sample || self.create!
      cert.destroy
      return cert
    rescue RESOURCE_NOT_FOUND
      retry if Cert.by_random.count > 0
      raise RECORD_NOT_FOUND
    end
  end

  def set_random
    self.random = rand
  end

  def attach_zip
    self.create_attachment :file => StringIO.new("dummy cert"), :name => zipname
  end

  def zipname
    'cert.zip'
  end

  def zipped
    attachments[zipname]
  end

end

app/models/unauthenticated_user.rb
# The nil object for the user class
class UnauthenticatedUser < Object

end

app/models/user.rb
class User < CouchRest::Model::Base

  include SRP::Authentication

  property :login, String, :accessible => true
  property :email, String, :accessible => true
  property :password_verifier, String, :accessible => true
  property :password_salt, String, :accessible => true

  validates :login, :password_salt, :password_verifier, :presence => true
  validates :login, :uniqueness => true

  timestamps!

  design do
    view :by_login
  end

  class << self
    def find_by_param(login)
      return find_by_login(login) || raise(RECORD_NOT_FOUND)
    end
  end

  def to_param
    self.login
  end

  def to_json(options={})
    super(options.merge(:only => ['login', 'password_salt']))
  end

  def salt
    password_salt.hex
  end

  def verifier
    password_verifier.hex
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) || UnauthenticatedUser.new
  end

  def logged_in?
    !current_user.is_a? UnauthenticatedUser
  end
end

app/controllers/certs_controller.rb
class CertsController < ApplicationController

  # GET /cert
  def show
    @cert = Cert.pick_from_pool
    send_data @cert.zipped, :filename => @cert.zipname
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_param(params[:login])
    session[:handshake] = @user.initialize_auth(params['A'].hex)
    render :json => { :B => session[:handshake].bb.to_s(16) }
  rescue RECORD_NOT_FOUND
    render :json => {:errors => {:login => ["unknown user"]}}
  end

  def update
    @user = User.find_by_param(params[:id])
    @server_auth = @user.authenticate!(params[:client_auth].hex, session.delete(:handshake))
    session[:user_id] = @user.id
    render :json => {:M2 => @server_auth.to_s(16)}
  rescue WRONG_PASSWORD
    session[:handshake] = nil
    render :json => {:errors => {"password" => ["wrong password"]}}
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  respond_to :json, :html

  def new
    @user = User.new
  end

  def create
    @user = User.create!(params[:user])
    respond_with(@user, :location => root_url, :notice => "Signed up!")
  rescue VALIDATION_FAILED => e
    @user = e.document
    respond_with(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def controller?(controller)
    params[:controller] == controller.to_s
  end

end

app/helpers/certs_helper.rb
module CertsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h3 Home

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%button.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button")
  %span.icon-bar
  %span.icon-bar
  %span.icon-bar
= link_to "Salticidae", root_path, :class => 'brand'
.pull-right
  %ul.nav
    - if logged_in?
      %li= current_user.login
      %li= link_to t(:logout), log_out_path
    - else
      %li= link_to t(:signup), sign_up_path
      %li= link_to t(:login), log_in_path
.nav-collapse.collapse
  %ul.nav
    %li{:class => controller?(:home) ? :active : ""}
      = link_to t(:home), root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Salticidae"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag params[:controller]
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/users/new.html.haml
%h2=t :signup
= simple_form_for @user do |f|
  %legend=t :signup_message
  = f.input :login, :input_html => { :id => :srp_username }
  = f.input :password, :required => true, :input_html => { :id => :srp_password }
  = f.input :password_confirmation, :required => true, :input_html => { :id => :srp_password_confirmation }
  = f.input :password_verifier, :as => :hidden, :input_html => { :id => :srp_password_verifier }
  = f.input :password_salt, :as => :hidden, :input_html => { :id => :srp_salt }
  = f.button :submit, :value => t(:signup), :class => 'btn-primary' 
  = link_to t(:cancel), root_url, :class => :btn